### ISSUE TITLE
Time frequency data export by Darbeliai plug-in

### ISSUE THREAD

**Issue by neurolinguist** [embar-/eeglab_darbeliai#60]
I am analyzing my EEG data by Darbeliai plug-in. It is very useful, and I am really grateful for Dr. Baranauskasgf for the efforts. I would like to export the spectrum power (beta band) for each experimental condition. I do not find the Events button to choose conditions. Can I select the events in the window of EEG spectrum and power? Thank you in advance.

Sincerely

**Comment by neurolinguist** [comment]
Dr. Baranauskasgf,

I am deeply grateful for your quick response. My experiment was within-designed 2-by-2, and my EEG data are epoched for event markers. In my experiment, two event markers correspond to one condition. I found a significant suppression in beta band for one of the experimental conditions against the control condition. I found this significant contrast by “Plot spectra” function of STUDY structure of EEGLAB. On the other hand, I have the responses by the participants for questionnaires in hand, and I would like to analyze the correlation between the spectral power for electrodes for each participant and their questionnaire responses. I thus want to export the spectral power in beta band for electrodes for four conditions separately. We can select specific event markers for exporting ERP. Is this possible in exporting spectral power? Thank you very much again.

Sincerely,

******************************************
Shingo Tokimoto, Ph.D.
in Linguistics and Psychology
Department of Foreign Languages
Mejiro University
4-31-1, Naka-Ochiai, Shinjuku, Tokyo,
161-8539, Japan
tokimoto@mejiro.ac.jp <mailto:tokimoto@mejiro.ac.jp>
******************************************

**Comment by embar-** [comment]
_EEG spectrum and power_ module is designed to be used with continuous data. Now usage with epoched data is possible, but note that for power spectrum calculation, it use moving window, by default 2 seconds. I suggest that more appropriate method to evaluate spectral power differences is to use ERSP functions from EEGLAB: pop_erspparams, std_erspplot. Thus it needs new/dedicated module of _Darbeliai_, adding option to select epochs would not be sufficient and would not be appropriate for such analysis. However _EEGLAB ERSP_ module is quite well developed, I don't see why we need this within _Darbeliai._

If you still really want to use Darbeliai for this, you can do this by these steps:
1. to select relevant epochs and save as separate EEG dataset. You can use _Darbeliai → Epoching by stimuli and responses_ for this. Or you can use lower level (command line) functions, including pop_selectevent.
2. Go _Darbeliai → EEG spectrum and power_ as you usually do.

**Comment by neurolinguist** [comment]
Dear Dr. Baranauskasgf,

I have understood the situation well. Thank you very much again.

Sincerely,

******************************************
Shingo Tokimoto, Ph.D.
in Linguistics and Psychology
Department of Foreign Languages
Mejiro University
4-31-1, Naka-Ochiai, Shinjuku, Tokyo,
161-8539, Japan
tokimoto@mejiro.ac.jp
******************************************

**Comment by embar-** [comment]
P.S. To extract data from EEGLAB you can do:

STUDY = pop_erspparams(STUDY, 'timerange', TIME_INTERVAL, 'freqrange',FREQUANCE_RANGE);

[STUDY erspdata ersptimes erspfreqs pgroup pcond pinter] = std_erspplot(STUDY,ALLEEG,'channels',YOUR_CHANNELS);

"erspdata" variable contains spectrum data in decibels. You need convert decibels to regular values, and then compute integral of spectrum – to obtain spectral power.

**Comment by neurolinguist** [comment]
Dear Dr. Baranauskasgf,

Thank you very much again. I am gradually understanding the EEGLAB script.

Sincerely,

******************************************
Shingo Tokimoto, Ph.D.
in Linguistics and Psychology
Department of Foreign Languages
Mejiro University
4-31-1, Naka-Ochiai, Shinjuku, Tokyo,
161-8539, Japan
tokimoto@mejiro.ac.jp
******************************************
