### ISSUE TITLE
Baseline correction in exporting ERP properties

### ISSUE THREAD

**Issue by neurolinguist** [embar-/eeglab_darbeliai#62]
I am deeply grateful for Darbeliai plug-in and the developer. Can I understand that we should correct the baseline before we export the ERP properties? Thank you in advance.

**Comment by embar-** [comment]
I you have doubts, you can compare results yourself after export without removing baseline, after removing baseline based on one time window, after based on another time window.

You should follow practice of your colleagues to decide about removing baseline (whether; and what time window if so) for specific ERP. 

In dialog of ERP export you will not remove baseline – it use data as it is.

If you need to remove baseline, look at bottom option "bsl" near "Epoch by"
https://github.com/embar-/eeglab_darbeliai/wiki/3.3.-Serial-processing

or you can use 
https://github.com/embar-/eeglab_darbeliai/wiki/3.4.-Complex-epoching

or you can use 
https://github.com/embar-/eeglab_darbeliai/wiki/3.7.-Custom-command
with code
`EEG = pop_rmbase( EEG, [time_from_milisec time_to_milisec]);`
