### ISSUE TITLE
Export ERP properties

### ISSUE THREAD

**Issue by neurolinguist** [embar-/eeglab_darbeliai#63]
I am deeply grateful for the excellent tool. I have 21 set files and I tried to export some ERP properties by an event marker. However, the property of only one file is not exported with the error message as below, where '35' is the event marker in question.

Warning: 'type' field value '35' not found

I can see the event marker 35 in the window of Plot Channel data. I re-processed the data file of the participant again, but the result is the same. Could you give me any ideas where I can find the reason of the error? Thank you in advance.

**Comment by embar-** [comment]
Can you please send/upload a problematic dataset for investigation?

**Comment by neurolinguist** [comment]
﻿[公式ニュース]
URLの安全性を無料で診断。ウィルスや詐欺サイトチェックが可能です。
見知らぬリンクをクリックする前には、まずはこちらで判定を！
サイトのキャプチャ機能もついて、ますます便利に！
https://ck.gigafile.nu/securl

ギガファイル便が複数ファイルを１つのファイルにまとめてダウンロードできる
「まとめてダウンロード」を実装。
さらに１ファイル１００Ｇまでアップロード可能に！！
https://gigafile.nu/

スクリーンショットはブラウザにペースト！
無料で使えて時間で消える画像貼りこみ共有サービス新登場！
https://ck.gigafile.nu/sukusho

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
無料大容量ファイル転送サービス「GigaFile（ギガファイル）便」
━━━━━━━━━━━━━━━━━━━━━━━ URL https://gigafile.nu/
■アップロード情報■
─────────────────────────────────────
ご利用いただきありがとうございます。アップロード情報をお届けします。

ZIPファイル名: gigafile-1220-ee42dc883b105e6f40e15b2c9d8e7b55.zip
まとめてダウンロードURL:
https://2.gigafile.nu/1220-ee42dc883b105e6f40e15b2c9d8e7b55
ダウンロード期限: 2018年12月20日（木）

FILE: ito_san.fdt
URL: https://2.gigafile.nu/1220-cfe1c17920a38f6c9d7ff25f0b58b01f0
削除KEY: e5b3
ダウンロード期限: 2018年12月20日（木）

FILE: ito_san.set
URL: https://2.gigafile.nu/1220-b007c31fde312cd21af03991aff651f1b
削除KEY: e12d
ダウンロード期限: 2018年12月20日（木）

========
メモ: 
EEG data file for Darbeliai

今後ともGigaFile（ギガファイル）便をよろしくお願い申し上げます。﻿
[PR]───────────────────────────────────
★ギガファイル便エンジニア募集中！★
この夏の仕事は熱く楽しく面白く！
仲間と一緒にチャレンジングしませんか！
詳しくはこちら
https://ck.gigafile.nu/saiyo0501
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
       GigaFile（ギガファイル）便 スマートフォンにも対応しました！！
                         https://gigafile.nu/                         

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Comment by neurolinguist** [comment]
Dear Dr. Mindaugas Baranauskas,

Thank you for the quick reply and your kindness. I have sent you the set file by a file transferring service. Thank you very much again.

Sincerely,

******************************************
Shingo Tokimoto, Ph.D.
in Linguistics and Psychology
Department of Foreign Languages
Mejiro University
4-31-1, Naka-Ochiai, Shinjuku, Tokyo,
161-8539, Japan
tokimoto@mejiro.ac.jp
******************************************

**Comment by embar-** [comment]
Thanks for dataset.
Problem was this: dataset contains numeric events, but pop_ERP_savybes 
use string.
To fix your problem in your computer, please open MATLAB, execute:

  edit pop_ERP_savybes

then press Ctrl+H, replace text

  EEGTMP = 
pop_loadset('filename',Rinkmena_,'filepath',KELIAS_,'loadmode','info');

into

  EEGTMP = eeg_ikelk(KELIAS_, Rinkmena_, 'loadmode','info');

Later I will release fixed version of Darbeliai

**Comment by embar-** [comment]
Note: there are two places/lines to change in pop_ERP_savybes.m (not 
only one)

**Comment by neurolinguist** [comment]
Dear Dr. Mindaugas Baranauskas,

The new code runs well. Thank you very much for the quick reply and the kindness.

Sincerely,

******************************************
Shingo Tokimoto, Ph.D.
in Linguistics and Psychology
Department of Foreign Languages
Mejiro University
4-31-1, Naka-Ochiai, Shinjuku, Tokyo,
161-8539, Japan
tokimoto@mejiro.ac.jp
******************************************

**Comment by embar-** [comment]
Fixed in Darbeliai v2018.12.14.1
