### ISSUE TITLE
Spectrum and Power error

### ISSUE THREAD

**Issue by orochimaverick** [embar-/eeglab_darbeliai#68]
Dear all, first of all nice plug-in. We use it in our lab constantly. However since we switched to Matlab R2019b and last version of EEGLAB we can't access the power spectrum (either from edf files or set files), this is the error that pops up:

Darbeliai v2019.02.01.1
EEGLAB 2019.1
MATLAB 9.7.0.1296695 (R2019b) Update 4 Windows it_IT
 
---------------
 
Time: 2020-03-11 15:30:23
Job: EEG spectrum and power
File: ?
 
Error! Please read info in console.

> eeg_spektr_galia:360
> checkbox_perziura_Callback:1867
> gui_mainfcn:95
> pop_eeg_spektrine_galia:88
 @(hObject,eventdata)pop_eeg_spektrine_galia('checkbox_perziura_Callback',hObject,eventdata,guidata(hObject))

 
---------------

**Comment by embar-** [comment]
Can you please look into MATLAB console (aka Command window) and check whether you see more relevant information regarding spectrum calculation and/or this error?

**Comment by orochimaverick** [comment]
Thank you for the fast response. I've tried again to "preview" the power spectrum in Cz on one edf file and this is what the matlab console posted:
2020-03-11 15:45:52
Warning: MATLAB:UndefinedFunction

Undefined function 'pwelch' for input arguments of type 'double'.

> spectcomp:941
> spectopo:347
> pop_spectopo:331
> eeg_spektr_galia:246
> checkbox_perziura_Callback:1867
> listbox1_Callback:1032
> gui_mainfcn:95
> pop_eeg_spektrine_galia:88

  @(hObject,eventdata)pop_eeg_spektrine_galia('listbox1_Callback',hObject,eventdata,guidata(hObject))

 
 
2020-03-11 15:45:52
Warning:

Error! Please read info in console.

> eeg_spektr_galia:360
> checkbox_perziura_Callback:1867
> listbox1_Callback:1032
> gui_mainfcn:95
> pop_eeg_spektrine_galia:88

  @(hObject,eventdata)pop_eeg_spektrine_galia('listbox1_Callback',hObject,eventdata,guidata(hObject))

**Comment by embar-** [comment]
MATLAB failed to find 'pwelch' function.
Did you installed Signal Processing Toolbox?

**Comment by orochimaverick** [comment]
You are absolutely correct and now it is working like a charm.

Sorry to have bothered you and thank you again.

Alessandro Piedimonte
University of Turin
