### ISSUE TITLE
Skipping artifact-contaminated portions for spectral analysis?

### ISSUE THREAD

**Issue by sdl3901** [embar-/eeglab_darbeliai#71]
Hello and thank you so much for this highly valuable plug-in. I was wondering if we're running the spectral power analysis on a set of continuous data if there is a way to skip over artifact-contaminated segments. I assume that if in EEGLAB I marked portions as bad that would not lead the plug-in to exclude that data from analysis. If I were to remove those portions before running the plugin I'm concerned about whether the voltage shifts from deleting bad portions would create a serious issue with proper spectral analysis (or would it not be that big a deal?). Any suggestions or recommendations based on your own experience dealing with artifacts in spectrally-analyzed data would be greatly appreciated. Cheers! --David Leland

**Comment by embar-** [comment]
Sorry for late answer. Spectral analysis in Darbeliai is a wrapper for the EEGLAB built-in function-file "pop_spectopo.m", though may transform results after that. Thus please see https://github.com/sccn/eeglab/blob/develop/functions/popfunc/pop_spectopo.m and https://github.com/sccn/eeglab/blob/develop/functions/sigprocfunc/spectopo.m for details regarding exact computations and consult EEGLAB team or EEGLAB mailing list.
